"""sim ledger tables

Revision ID: 012
Revises: 011
Create Date: 2026-07-30 14:12:06.694504
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '012'
down_revision: Union[str, None] = '011'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('heartbeats',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('last_beat_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('master_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('tighten_only', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('recommendations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=8, scale=3), nullable=False),
    sa.Column('shortlist_rank', sa.Integer(), nullable=True),
    sa.Column('phase', sa.String(length=10), nullable=False),
    sa.Column('phase_reason', sa.Text(), nullable=True),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'trade_date', name='uq_recommendation_symbol_date')
    )
    op.create_index(op.f('ix_recommendations_symbol'), 'recommendations', ['symbol'], unique=False)
    op.create_index(op.f('ix_recommendations_trade_date'), 'recommendations', ['trade_date'], unique=False)
    op.create_table('safety_state',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('scope', sa.String(length=50), nullable=False),
    sa.Column('halted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('halted_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paused_until', sa.Date(), nullable=True),
    sa.Column('peak_equity', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scope')
    )
    op.create_table('sim_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), server_default='default', nullable=False),
    sa.Column('is_system', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('starting_capital', sa.Numeric(precision=18, scale=2), server_default=sa.text('2000'), nullable=False),
    sa.Column('cash', sa.Numeric(precision=18, scale=2), server_default=sa.text('2000'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_sim_account_user_name')
    )
    op.create_index(op.f('ix_sim_accounts_user_id'), 'sim_accounts', ['user_id'], unique=False)
    op.create_table('account_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('equity', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('cash', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('open_positions', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['sim_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'snapshot_date', name='uq_snapshot_account_date')
    )
    op.create_index(op.f('ix_account_snapshots_account_id'), 'account_snapshots', ['account_id'], unique=False)
    op.create_table('sim_positions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=10), server_default='open', nullable=False),
    sa.Column('shares', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('avg_cost', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('stop', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('r_unit', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('high_water', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('adds_done', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('reversal_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('bars_held', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('close_reason', sa.String(length=30), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['sim_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sim_positions_account_id'), 'sim_positions', ['account_id'], unique=False)
    op.create_index(op.f('ix_sim_positions_symbol'), 'sim_positions', ['symbol'], unique=False)
    op.create_index('uq_sim_position_open', 'sim_positions', ['account_id', 'symbol'], unique=True, postgresql_where=sa.text("status = 'open'"))
    op.create_table('sim_orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('position_id', sa.UUID(), nullable=True),
    sa.Column('recommendation_id', sa.UUID(), nullable=True),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('side', sa.String(length=4), nullable=False),
    sa.Column('qty', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('order_type', sa.String(length=10), server_default='market', nullable=False),
    sa.Column('status', sa.String(length=10), server_default='pending', nullable=False),
    sa.Column('reason', sa.String(length=30), nullable=False),
    sa.Column('idempotency_key', sa.String(length=120), nullable=False),
    sa.Column('reject_reason', sa.Text(), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('filled_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['sim_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['position_id'], ['sim_positions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index(op.f('ix_sim_orders_account_id'), 'sim_orders', ['account_id'], unique=False)
    op.create_index(op.f('ix_sim_orders_symbol'), 'sim_orders', ['symbol'], unique=False)
    op.create_table('sim_fills',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('price', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('raw_price', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('qty', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('commission', sa.Numeric(precision=18, scale=6), server_default=sa.text('0'), nullable=False),
    sa.Column('filled_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['sim_orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id')
    )
    # NOTE: autogenerate also proposed ai_analysis_results enum type changes —
    # that is PRE-EXISTING drift (known since 011), out of this migration's
    # scope and deliberately dropped here.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sim_fills')
    op.drop_index(op.f('ix_sim_orders_symbol'), table_name='sim_orders')
    op.drop_index(op.f('ix_sim_orders_account_id'), table_name='sim_orders')
    op.drop_table('sim_orders')
    op.drop_index('uq_sim_position_open', table_name='sim_positions', postgresql_where=sa.text("status = 'open'"))
    op.drop_index(op.f('ix_sim_positions_symbol'), table_name='sim_positions')
    op.drop_index(op.f('ix_sim_positions_account_id'), table_name='sim_positions')
    op.drop_table('sim_positions')
    op.drop_index(op.f('ix_account_snapshots_account_id'), table_name='account_snapshots')
    op.drop_table('account_snapshots')
    op.drop_index(op.f('ix_sim_accounts_user_id'), table_name='sim_accounts')
    op.drop_table('sim_accounts')
    op.drop_table('safety_state')
    op.drop_index(op.f('ix_recommendations_trade_date'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_symbol'), table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_table('master_settings')
    op.drop_table('heartbeats')
    # ### end Alembic commands ###
